### ISSUE TITLE
self import is not allowed

### ISSUE THREAD

**Issue by zhuxubin01** [sorcererxw/protoc-gen-go-grpc-mock#1]
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/23697363/158956527-1d2cbfee-1fed-4d73-83f2-3678bd319d7c.png">

**Comment by sorcererxw** [comment]
Could you please provide a demo to reproduce the problem?

**Comment by wdullaer** [comment]
I just bumped into this.
I think this check here is not sufficient: https://github.com/sorcererxw/protoc-gen-go-grpc-mock/blob/master/main.go#L39-L41

Unless the import starts with `./` explicitly, you treat it as an external import.
But this does not need to be the case

```proto
import 'file2.proto'
```

This will happily import `file2.proto` from the current directory if it's there.
